import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const PAGE_FILE = new URL('../../app/gnr8/agency/clients/[clientId]/sites/[siteId]/SiteWorkspacePage.tsx', import.meta.url)

test('Site Workspace preview view exposes raw-template asset fidelity controls', async () => {
  const source = await readFile(PAGE_FILE, 'utf8')

  assert.equal(source.includes('buildMultiPageRawTemplatePreviewDiagnostics'), true)
  assert.equal(source.includes('Raw Preview Asset Fidelity'), true)
  assert.equal(source.includes('routePath'), true)
  assert.equal(source.includes('rawFilePath'), true)
  assert.equal(source.includes('htmlByteLengthBeforeRewrite'), true)
  assert.equal(source.includes('htmlByteLengthAfterRewrite'), true)
  assert.equal(source.includes('rewrittenLinkCount'), true)
  assert.equal(source.includes('assetRefsInspected'), true)
  assert.equal(source.includes('assetRefsMissing'), true)
  assert.equal(source.includes('externalAssetRefsPreserved'), true)
  assert.equal(source.includes('scripts: found='), true)
  assert.equal(source.includes('script loading: local rewritten='), true)
  assert.equal(source.includes('blocked script reasons'), true)
  assert.equal(source.includes('Script policy evidence'), true)
  assert.equal(source.includes('duplicateRootGuard'), true)
  assert.equal(source.includes('rawPreviewDuplicateGuardEvidence'), true)
  assert.equal(source.includes('mapEmbed'), true)
  assert.equal(source.includes('rawPreviewEmbedEvidence'), true)
  assert.equal(source.includes('detectedFontFamilies'), true)
  assert.equal(source.includes('top missing asset refs'), true)
  assert.equal(source.includes('rawPreviewDiagnostics.links.map'), true)
  assert.equal(source.includes('link.href'), true)
})

test('Site Workspace labels import version metadata and preview modes distinctly', async () => {
  const source = await readFile(PAGE_FILE, 'utf8')

  assert.equal(source.includes('Latest Import Run ID'), true)
  assert.equal(source.includes('Latest Import siteVersionId'), true)
  assert.equal(source.includes('Latest Import artifactId'), true)
  assert.equal(source.includes('Selected Workspace siteVersionId'), true)
  assert.equal(source.includes('GNR8 Transformed Preview (experimental)'), true)
  assert.equal(source.includes('Raw Imported Preview'), true)
  assert.equal(source.includes('Open Original Preview'), true)
  assert.equal(source.includes('Open GNR8 Transformed Preview (experimental)'), true)
  assert.equal(source.includes('primaryPreviewLabel'), true)
  assert.equal(source.includes('showExperimentalTransformedPreview'), true)
  assert.equal(source.includes('Latest Raw Preview Validation'), true)
  assert.equal(source.includes('No raw preview validation evidence captured.'), true)
  assert.equal(source.includes('responseStatus'), true)
  assert.equal(source.includes('responseBytes'), true)
  assert.equal(source.includes('Public/Published Preview'), true)
  assert.equal(source.includes('Root Raw Multi-Page Preview URL'), true)
  assert.equal(source.includes('First Child Raw Multi-Page Preview URL'), true)
  assert.equal(source.includes('Preview Mode Warning'), true)
  assert.equal(source.includes('Open Public/Published Preview'), true)
})

test('Site Workspace source exposes Reconstruction Readiness labels', async () => {
  const source = await readFile(PAGE_FILE, 'utf8')

  assert.equal(source.includes('Reconstruction Readiness'), true)
  assert.equal(source.includes('Readiness Level'), true)
  assert.equal(source.includes('Blocker Count'), true)
  assert.equal(source.includes('Required Evidence Present'), true)
  assert.equal(source.includes('Required Evidence Missing'), true)
  assert.equal(source.includes('Optional Evidence Present'), true)
  assert.equal(source.includes('Optional Evidence Missing'), true)
  assert.equal(source.includes('Confidence Inputs'), true)
  assert.equal(source.includes('Next Recommended Capture Expansion'), true)
  assert.equal(source.includes('NOT_READY'), true)
  assert.equal(source.includes('MINIMUM_READY'), true)
  assert.equal(source.includes('RECOMMENDED'), true)
  assert.equal(source.includes('HIGH_CONFIDENCE'), true)
})
