export type MultipageDiagnosticCode =
  | 'MULTIPAGE_IMPORT_STARTED'
  | 'MULTIPAGE_DISCOVERY_COMPLETED'
  | 'MULTIPAGE_ROUTE_DISCOVERED'
  | 'MULTIPAGE_ROUTE_DUPLICATE_SKIPPED'
  | 'MULTIPAGE_ROUTE_LIMIT_REACHED'
  | 'MULTIPAGE_DEPTH_LIMIT_REACHED'
  | 'MULTIPAGE_EXTERNAL_LINK_SKIPPED'
  | 'MULTIPAGE_ASSET_LINK_SKIPPED'
  | 'MULTIPAGE_ROUTE_CLASSIFIED'
  | 'MULTIPAGE_NAV_TREE_BUILT'
  | 'MULTIPAGE_SHARED_REGION_INFERRED'
  | 'MULTIPAGE_TEMPLATE_FAMILY_INFERRED'
  | 'MULTIPAGE_DISCOVERY_DEGRADED'
  | 'MULTIPAGE_DISCOVERY_PARTIAL'
  | 'MULTIPAGE_CANONICAL_HOST_EQUIVALENCE_APPLIED'
  | 'MULTIPAGE_FINAL_URL_ACCEPTED_CANONICAL_HOST'
  | 'MULTIPAGE_FINAL_URL_REJECTED_CROSS_ORIGIN'
  | 'SITEMAP_DISCOVERY_STARTED'
  | 'SITEMAP_DISCOVERY_SUCCEEDED'
  | 'SITEMAP_DISCOVERY_NOT_FOUND'
  | 'SITEMAP_DISCOVERY_FAILED'
  | 'SITEMAP_URL_DISCOVERED'
  | 'SITEMAP_URL_SKIPPED'
  | 'SITEMAP_LIMIT_REACHED'
  | 'SITEMAP_NESTED_DISCOVERY_STARTED'
  | 'SITEMAP_NESTED_DISCOVERY_SUCCEEDED'
  | 'ROBOTS_DISCOVERY_STARTED'
  | 'ROBOTS_DISCOVERY_SUCCEEDED'
  | 'ROBOTS_DISCOVERY_NOT_FOUND'
  | 'ROBOTS_DISCOVERY_FAILED'
  | 'ROBOTS_SITEMAP_DECLARATION_FOUND'
  | 'ROBOTS_ROUTE_ALLOWED'
  | 'ROBOTS_ROUTE_DISALLOWED'
  | 'ROBOTS_ROUTE_UNKNOWN'
  | 'ROBOTS_RULES_APPLIED'
  | 'ROBOTS_SITEMAP_DECLARATION_MISSING'

function cleanPart(value: string | null | undefined): string {
  return String(value ?? '').trim().replace(/\s+/g, ' ')
}

export function diagnosticEntry(code: MultipageDiagnosticCode, detail?: string | null): string {
  const normalized = cleanPart(detail)
  return normalized ? `${code}:${normalized}` : code
}

export function sortDiagnostics(diagnostics: string[]): string[] {
  return [...new Set(diagnostics.map((entry) => cleanPart(entry)).filter(Boolean))].sort((a, b) => a.localeCompare(b))
}
