export const fixtureSimpleLandingHtml = [
  "<!doctype html>",
  "<html>",
  "<head><title>Simple Landing</title></head>",
  "<body>",
  '  <header class="site-header">',
  '    <nav class="site-nav"><a href="#home">Home</a><a href="#about">About</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></nav>',
  "  </header>",
  '  <section id="hero" class="hero banner">',
  "    <h1>Transport Across Europe</h1>",
  "    <p>Fast and safe vehicle transport with transparent logistics.</p>",
  '    <img src="/assets/hero.jpg" alt="fleet" />',
  "  </section>",
  '  <section id="about" class="content section">',
  "    <h2>About Us</h2>",
  "    <p>We provide end-to-end transport planning, customs support, and dispatch operations for cross-border cargo routes.</p>",
  "    <p>Our operations team runs fixed weekly lanes and custom urgent shipments with route-level visibility.</p>",
  "  </section>",
  '  <section id="gallery" class="gallery">',
  '    <img src="/assets/g1.jpg" alt="truck-1" />',
  '    <img src="/assets/g2.jpg" alt="truck-2" />',
  '    <img src="/assets/g3.jpg" alt="truck-3" />',
  '    <img src="/assets/g4.jpg" alt="truck-4" />',
  "  </section>",
  '  <section id="contact" class="contact">',
  "    <h2>Contact</h2>",
  '    <form action="/lead" method="post">',
  "      <input name=\"name\" />",
  "      <input name=\"email\" />",
  "      <textarea name=\"message\"></textarea>",
  "      <button type=\"submit\">Send</button>",
  "    </form>",
  "  </section>",
  '  <footer class="site-footer">',
  "    <p>Contact +386 1 111 111</p>",
  '    <div class="legal">Privacy Policy | Terms</div>',
  "  </footer>",
  "</body>",
  "</html>",
].join("\n");

export const fixtureHeavyNavHtml = [
  "<!doctype html>",
  "<html>",
  "<head><title>Heavy Nav</title></head>",
  "<body>",
  '  <div class="top menu nav">',
  "    <h1>Menu</h1>",
  '    <a href="/">Home</a><a href="/about">About</a><a href="/services">Services</a><a href="/fleet">Fleet</a><a href="/faq">FAQ</a><a href="/contact">Contact</a><a href="/legal">Legal</a>',
  "  </div>",
  '  <section class="hero">',
  "    <h1>Reliable Logistics</h1>",
  "    <p>Route-optimized transport for automotive and freight operators.</p>",
  '    <img src="/assets/hero-heavy.jpg" alt="hero" />',
  "  </section>",
  '  <section class="content">',
  "    <h2>Operations</h2>",
  "    <p>Our control tower coordinates dispatch windows, border transitions, and incident response across multiple corridors.</p>",
  "  </section>",
  "  <footer><p>Copyright 2026 Example Transport</p></footer>",
  "</body>",
  "</html>",
].join("\n");

export const fixtureMaverHtml = [
  "<!doctype html>",
  "<html>",
  "<head><title>Transporti Maver</title></head>",
  "<body>",
  "  <header>",
  "    <div class=\"brand\">TRANSPORTI MAVER D.O.O.</div>",
  "    <nav>",
  '      <a href="#home">Home</a><a href="#about">O nas</a><a href="#gallery">Galerija</a><a href="#contact">Kontakt</a>',
  "    </nav>",
  "  </header>",
  "  <main>",
  '    <section class="hero intro">',
  "      <h1>Prevozi Po Evropi</h1>",
  "      <p>Dolgoletne izkusnje in vozni park za varne mednarodne prevoze.</p>",
  '      <img src="/assets/hero.svg" alt="hero" />',
  "    </section>",
  '    <section class="content">',
  "      <h2>O Podjetju</h2>",
  "      <p>Nase podjetje ima dolgo tradicijo in stalne relacije po Evropi.</p>",
  "      <p>Kamioni izpolnjujejo EU standard EUR 6 in omogocajo hitro dostavo.</p>",
  "    </section>",
  '    <section class="gallery">',
  '      <img src="/assets/image/1.jpg" alt="1" />',
  '      <img src="/assets/image/2.jpg" alt="2" />',
  '      <img src="/assets/image/3.jpg" alt="3" />',
  "    </section>",
  '    <section id="contact">',
  "      <h2>Kontakt</h2>",
  '      <form><input name="name" /><input name="email" /><button>Poslji</button></form>',
  "    </section>",
  "  </main>",
  '  <footer class="site-footer">',
  "    <p>Dolenjska cesta 328, Lavrica</p>",
  '    <div class="legal">Pravne informacije | Privacy | Terms</div>',
  "  </footer>",
  "</body>",
  "</html>",
].join("\n");

export const layoutGraphFixtures = {
  "fixture-simple-landing.html": fixtureSimpleLandingHtml,
  "fixture-heavy-nav.html": fixtureHeavyNavHtml,
  "fixture-maver.html": fixtureMaverHtml,
} as const;
