export const PREVIEW_RUNTIME_DIAGNOSTIC = {
  PREPARATION_STARTED: "PREVIEW_RUNTIME_PREPARATION_STARTED",
  FINAL_SITE_MODEL_AVAILABLE: "PREVIEW_FINAL_SITE_MODEL_AVAILABLE",
  FINAL_SITE_MODEL_UNAVAILABLE: "PREVIEW_FINAL_SITE_MODEL_UNAVAILABLE",
  RENDERER_CONTRACT_CREATED: "PREVIEW_RENDERER_CONTRACT_CREATED",
  RENDERER_CONTRACT_UNAVAILABLE: "PREVIEW_RENDERER_CONTRACT_UNAVAILABLE",
  REAL_REACT_RENDER_SELECTED: "PREVIEW_REAL_REACT_RENDER_SELECTED",
  REAL_REACT_RENDER_DEGRADED: "PREVIEW_REAL_REACT_RENDER_DEGRADED",
  FALLBACK_RENDER_SELECTED: "PREVIEW_FALLBACK_RENDER_SELECTED",
  RENDERER_RUNTIME_FAILED: "PREVIEW_RENDERER_RUNTIME_FAILED",
  PREVIEW_MODE_FROM_RENDERED_CAPTURE: "PREVIEW_MODE_FROM_RENDERED_CAPTURE",
  FALLBACK_BLOCKED_RENDER_AVAILABLE: "FALLBACK_BLOCKED_RENDER_AVAILABLE",
  MODE_PERSISTED: "PREVIEW_MODE_PERSISTED",
  SEMANTIC_PREVIEW_RENDER_STARTED: "SEMANTIC_PREVIEW_RENDER_STARTED",
  SEMANTIC_PREVIEW_RENDER_COMPLETED: "SEMANTIC_PREVIEW_RENDER_COMPLETED",
  SEMANTIC_PREVIEW_RENDER_EMPTY: "SEMANTIC_PREVIEW_RENDER_EMPTY",
  SEMANTIC_PREVIEW_SELECTED: "SEMANTIC_PREVIEW_SELECTED",
  SEMANTIC_PREVIEW_IMAGE_UNRESOLVED: "SEMANTIC_PREVIEW_IMAGE_UNRESOLVED",
  RAW_TEMPLATE_PREVIEW_SELECTED: "RAW_TEMPLATE_PREVIEW_SELECTED",
  RAW_TEMPLATE_PREVIEW_RENDERED: "RAW_TEMPLATE_PREVIEW_RENDERED",
  RAW_TEMPLATE_ASSET_RESOLVED: "RAW_TEMPLATE_ASSET_RESOLVED",
  RAW_TEMPLATE_ASSET_MISSING: "RAW_TEMPLATE_ASSET_MISSING",
  MULTIPAGE_ROUTE_MAP_SELECTED: "MULTIPAGE_ROUTE_MAP_SELECTED",
  MULTIPAGE_ROUTE_MAP_MISS: "MULTIPAGE_ROUTE_MAP_MISS",
  MULTIPAGE_ROUTE_MAP_FILE_MISSING: "MULTIPAGE_ROUTE_MAP_FILE_MISSING",
  MULTIPAGE_ROUTE_MAP_DISABLED: "MULTIPAGE_ROUTE_MAP_DISABLED",
  MULTIPAGE_ROUTE_MAP_ROOT_SELECTED: "MULTIPAGE_ROUTE_MAP_ROOT_SELECTED",
} as const;

export function withSortedDiagnostics(diagnostics: string[]): string[] {
  return [...new Set(diagnostics.filter((value) => value.trim().length > 0))].sort((a, b) => a.localeCompare(b));
}
